### ISSUE TITLE
Please add support for tags

### ISSUE THREAD

**Issue by ransomcarroll** [mremi/Flowdock#1]
Being able to easily add tags with this interface would be amazing.

Thanks!

**Comment by mremi** [comment]
Hi,

Are you talking about this:
https://github.com/mremi/Flowdock/blob/master/src/Mremi/Flowdock/Api/Push/BaseMessage.php#L91 ?

**Comment by mremi** [comment]
Ping @ransomcarroll

**Comment by mremi** [comment]
No news, I close this issue, reopen it if need.

**Comment by ransomcarroll** [comment]
Sorry, my inbox filtered this out. It does look like you are supporting tags, not sure how I overlooked that.

Thanks
